# These settings were set by the catalyst build script that automatically
# built this stage.
# Please consult /usr/share/portage/config/make.conf.example for a more
# detailed example.
COMMON_FLAGS="-O2 -march=znver2 -pipe"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

MAKEOPTS="-j4 -l5"

# NOTE: This stage was built with the bindist USE flag enabled

USE=" \
X -kde -gnome -systemd wayland elogind \
udev dbus \
pipewire alsa pulseadio caro \
opengl vulkan \
vaapi vdpau webp sound-server
ffmpeg exyra \
jpeg png svg webp \
"

INPUT_DEVICES="libinput"
VIDEO_CARDS="amdgpu radeonsi"

ACCEPT_LICENSE="*"

# This sets the language of build output to English.
# Please keep this setting intact when reporting bugs.
LC_MESSAGES=C.UTF-8
GRUB_PLATFORMS="efi-64"
